baseurl = "http://garado.dev"
title = "Alexis Garado"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = ""

[markup.highlight]
style = "github-dark"

[params]
  author = "Alexis Garado"
  info = "Embedded software engineer"
  description = "Alexis Garado's personal website"
  keywords = "blog,developer,personal"
  gravatar = "alexisgarado@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2021

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/garado/"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 2
  url = "mailto:alexisgarado@gmail.com"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://linkedin.com/in/garado"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Resume"
  weight = 2
  url = "https://resume.garado.dev/"
